version: '3' 
services: 
  next_starter:
    container_name: 'next-starter'
    restart: unless-stopped
    image: node:lts
    command: npm run dev
    ports: 
      - '3000:3000'
    volumes:
      # bind current directory to /service/next_starter read/write
      # this allows hmr to happen
      - .:/service/next_starter
    working_dir: /service/next_starter
    env_file:
      - .env