name: Running build and tests

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Type Check
      run: npm run type-check

    - name: Run tests
      run: npm run test:ci
  
    - name: Build app
      run: npm run build --if-present
      env:
          CI: true
